export interface JsonData {
    data: {
      [key: string]: string;
    };
    total_items: number;
    total_pages: number;
    per_page: number;
    current_page: number;
  }

export const jsonData: JsonData = {
    "data": {
        "Dog": "🐶",
        "Cat": "🐱",
        "Mouse": "🐭",
        "Hamster": "🐹",
        "Rabbit": "🐰",
        "Fox": "🦊",
        "Bear": "🐻",
        "Panda": "🐼",
        "Koala": "🐨",
        "Tiger": "🐯",
        "Lion": "🦁",
        "Cow": "🐮",
        "Pig": "🐷",
        "Pig Face": "🐽",
        "Frog": "🐸",
        "Monkey Face": "🐵",
        "See-No-Evil Monkey": "🙈",
        "Hear-No-Evil Monkey": "🙉",
        "Speak-No-Evil Monkey": "🙊",
        "Chicken": "🐔",
        "Penguin": "🐧",
        "Bird": "🐦",
        "Baby Chick": "🐤",
        "Hatching Chick": "🐣",
        "Duck": "🦆",
        "Swan": "🦢",
        "Eagle": "🦅",
        "Owl": "🦉",
        "Bat": "🦇",
        "Wolf": "🐺",
        "Boar": "🐗",
        "Horse": "🐴",
        "Unicorn": "🦄",
        "Honeybee": "🐝",
        "Bug": "🐛",
        "Butterfly": "🦋",
        "Snail": "🐌",
        "Octopus": "🐙",
        "Turtle": "🐢",
        "Crab": "🦀",
        "Blowfish": "🐡",
        "Dolphin": "🐬",
        "Shark": "🦈",
        "Fish": "🐟",
        "Tropical Fish": "🐠",
        "Whale": "🐳",
        "Whale Shark": "🦈",
        "Crocodile": "🐊",
        "Leopard": "🐆",
        "Tiger Face": "🐅",
        "Water Buffalo": "🐃",
        "Ox": "🐂",
        "Cow Face": "🐄",
        "Dromedary Camel": "🐪",
        "Camel": "🐫",
        "Elephant": "🐘",
        "Rhinoceros": "🦏",
        "Gorilla": "🦍",
        "Racehorse": "🐎",
        "Pig Nose": "🐽",
        "Sheep": "🐑",
        "Goat": "🐐",
        "Ram": "🐏",
        "Deer": "🦌",
        "Giraffe": "🦒",
        "Hippopotamus": "🦛",
        "Zebra": "🦓",
        "Lizard": "🦎",
        "Snake": "🐍",
        "Dragon Face": "🐲",
        "Dragon": "🐉",
        "Spouting Whale": "🐳",
        "Wolf Face": "🐺",
        "Monkey": "🐒"
    },
    "total_items": 74,
    "total_pages": 1,
    "per_page": 100,
    "current_page": 1
}